#ddev-generated
services:
  gitlab:
    container_name: ddev-${DDEV_SITENAME}-gitlab
    image: gitlab/gitlab-ee:16.9.2-ee.0
    restart: always
    environment:
      VIRTUAL_HOST: git.local
      HTTP_EXPOSE: 80
      HTTPS_EXPOSE: 443
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://git.local'
        nginx['redirect_http_to_https'] = true
        letsencrypt['enable'] = false
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
        gitlab_rails['omniauth_auto_link_ldap_user'] = true
        gitlab_rails['omniauth_block_auto_created_users'] = true
        # nginx['ssl_certificate'] = "/mnt/ddev_config/traefik/certs/gitlab.crt"
        # nginx['ssl_certificate_key'] = "/mnt/ddev_config/traefik/certs/gitlab.key"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
      - ".:/mnt/ddev_config"
    shm_size: '256m'
    external_links:
      - "ddev-router:accounts.ddev.site"

  web:
    links:
      - gitlab:$DDEV_HOSTNAME
      - gitlab:git.local

volumes:
  gitlab:
