services:
  gitlab:
    environment:
      VIRTUAL_HOST: gitlab.ddev.site
      HTTP_EXPOSE: 80:80,8025:8025
      HTTPS_EXPOSE: 443:80,8026:8025

    container_name: ddev-${DDEV_SITENAME}-gitlab
    image: gitlab/gitlab-ce:16.9.2-ce.0
    build:
      context: './gitlab/docker'

    restart: always
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    volumes:
      - './gitlab/etc/gitlab:/etc/gitlab'
      - ".:/mnt/ddev_config"
    shm_size: '256m'
    external_links:
      - "ddev-router:oauth.ddev.site"

    healthcheck:
      test: ["CMD-SHELL", "curl --fail -s gitlab.ddev.site"]
      timeout: 180s

  web:
    external_links:
      - "ddev-router:gitlab.ddev.site"

volumes:
  gitlab:
